import {
  AppWindow,
  Folder,
  LayoutGrid,
  FileText,
  Mail,
  Calendar,
  Database,
  Users,
  Settings,
  Shield,
  BarChart,
  Truck,
  Wrench,
  Globe,
  ExternalLink,
  Lock,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Clock,
  CreditCard,
  DollarSign,
  FileSpreadsheet,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Landmark,
  Laptop,
  LineChart,
  MapPin,
  MessageSquare,
  Monitor,
  Package,
  Phone,
  Printer,
  Server,
  ShoppingCart,
  Smartphone,
  Target,
  Video,
  Wallet,
  Wifi,
  Zap,
  ClipboardList,
  Factory,
  Fuel,
  HardHat,
  Pickaxe,
  Receipt,
  Scale,
  Warehouse,
  HeartPulse,
  Activity,
  Stethoscope,
  Pill,
  Syringe,
  Cross,
  CirclePlus,
  Ambulance,
  AlertTriangle,
  AlertCircle,
  ShieldCheck,
  ShieldAlert,
  Flame,
  Siren,
  BadgeCheck,
  ClipboardCheck,
  FileCheck,
  FileWarning,
  Eye,
  Megaphone,
  Bell,
  BookOpen,
  GraduationCap,
  Layers,
  PieChart,
  TrendingUp,
} from "lucide-react";

export const iconMap: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  AppWindow,
  Folder,
  LayoutGrid,
  FileText,
  Mail,
  Calendar,
  Database,
  Users,
  Settings,
  Shield,
  BarChart,
  Truck,
  Wrench,
  Globe,
  ExternalLink,
  Lock,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CreditCard,
  DollarSign,
  Landmark,
  Receipt,
  Scale,
  Wallet,
  Clock,
  ClipboardList,
  Target,
  HardDrive,
  Laptop,
  Monitor,
  Server,
  Smartphone,
  Wifi,
  Zap,
  Headphones,
  MessageSquare,
  Phone,
  Video,
  FileSpreadsheet,
  LineChart,
  Factory,
  Home,
  MapPin,
  Package,
  Printer,
  ShoppingCart,
  Warehouse,
  Fuel,
  HardHat,
  Pickaxe,
  Heart,
  HeartPulse,
  Activity,
  Stethoscope,
  Pill,
  Syringe,
  Cross,
  CirclePlus,
  Ambulance,
  AlertTriangle,
  AlertCircle,
  ShieldCheck,
  ShieldAlert,
  Flame,
  Siren,
  BadgeCheck,
  ClipboardCheck,
  FileCheck,
  FileWarning,
  Eye,
  Megaphone,
  Bell,
  BookOpen,
  GraduationCap,
  Layers,
  PieChart,
  TrendingUp,
};

export function AppIcon({ icon, iconType, size = 24, className }: { icon?: string; iconType: string; size?: number; className?: string }) {
  if (!icon) {
    return <AppWindow size={size} className={className} />;
  }

  if (iconType === "emoji") {
    return <span className={size <= 16 ? "text-sm" : "text-2xl"}>{icon}</span>;
  }

  if (iconType === "url") {
    return <img src={icon} alt="" className={size <= 16 ? "h-4 w-4 object-contain" : "h-6 w-6 object-contain"} />;
  }

  // lucide icon
  const IconComponent = iconMap[icon] || AppWindow;
  return <IconComponent size={size} className={className} />;
}
